import "server-only";

import { fromProjectRoot } from "@/lib/db/env";

import { createReadStream } from "node:fs";
import { mkdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { Readable } from "node:stream";

import {
  DeleteObjectCommand,
  GetObjectCommand,
  HeadObjectCommand,
  PutObjectCommand,
  S3Client,
} from "@aws-sdk/client-s3";

/**
 * Storage is abstracted so uploaded files can move from the local Docker
 * volume to S3-compatible object storage without touching call sites.
 *
 * Files are never written into `public/`: that directory is a build-time asset
 * folder, and anything placed there would be publicly readable regardless of
 * whether the record is marked private. Everything is served through a route
 * handler that applies authorisation.
 */

export type StoredObject = {
  key: string;
  size: number;
};

export interface StorageAdapter {
  readonly name: string;
  put(key: string, body: Buffer, contentType: string): Promise<StoredObject>;
  get(key: string): Promise<Buffer>;
  stream(key: string): Promise<Readable>;
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
  size(key: string): Promise<number>;
}

/**
 * Object keys are generated by the application, never taken from a filename.
 * This guards the boundary anyway, so a bug upstream cannot escape the root.
 */
export function assertSafeKey(key: string): void {
  if (!key || key.startsWith("/") || key.includes("\\")) {
    throw new Error(`Unsafe storage key: ${key}`);
  }
  const normalised = path.posix.normalize(key);
  if (
    normalised !== key ||
    normalised.split("/").some((segment) => segment === ".." || segment === "")
  ) {
    throw new Error(`Unsafe storage key: ${key}`);
  }
}

class LocalStorageAdapter implements StorageAdapter {
  readonly name = "local";
  private readonly root: string;

  constructor(root: string) {
    this.root = path.resolve(root);
  }

  private resolve(key: string): string {
    assertSafeKey(key);
    const full = path.resolve(this.root, key);
    // Defence in depth: the resolved path must stay inside the root.
    if (full !== this.root && !full.startsWith(this.root + path.sep)) {
      throw new Error(`Storage key escapes the storage root: ${key}`);
    }
    return full;
  }

  async put(key: string, body: Buffer): Promise<StoredObject> {
    const full = this.resolve(key);
    await mkdir(path.dirname(full), { recursive: true });
    await writeFile(full, body, { mode: 0o640 });
    return { key, size: body.byteLength };
  }

  async get(key: string): Promise<Buffer> {
    const { readFile } = await import("node:fs/promises");
    return readFile(this.resolve(key));
  }

  async stream(key: string): Promise<Readable> {
    const full = this.resolve(key);
    await stat(full); // surface a missing file before streaming starts
    return createReadStream(full);
  }

  async delete(key: string): Promise<void> {
    await rm(this.resolve(key), { force: true });
  }

  async exists(key: string): Promise<boolean> {
    assertSafeKey(key);
    try {
      await stat(this.resolve(key));
      return true;
    } catch {
      return false;
    }
  }

  async size(key: string): Promise<number> {
    const stats = await stat(this.resolve(key));
    return stats.size;
  }
}

type S3Config = {
  bucket: string;
  region: string;
  endpoint?: string;
  accessKeyId: string;
  secretAccessKey: string;
  forcePathStyle: boolean;
};

/**
 * Reads the S3 configuration, naming every missing variable at once rather
 * than failing on the first — a deploy with three unset variables should not
 * take three attempts to discover.
 */
function readS3Config(): S3Config {
  const env = process.env;
  const missing = ["STORAGE_S3_BUCKET", "STORAGE_S3_ACCESS_KEY_ID", "STORAGE_S3_SECRET_ACCESS_KEY"].filter(
    (name) => !env[name],
  );
  if (missing.length > 0) {
    throw new Error(
      `STORAGE_DRIVER is "s3" but ${missing.join(", ")} ${missing.length === 1 ? "is" : "are"} not set. ` +
        "See .env.example.",
    );
  }

  const endpoint = env.STORAGE_S3_ENDPOINT || undefined;
  return {
    bucket: env.STORAGE_S3_BUCKET!,
    // Non-AWS stores (R2, Neon, MinIO) accept any region; "auto" is R2's own.
    region: env.STORAGE_S3_REGION || "auto",
    endpoint,
    accessKeyId: env.STORAGE_S3_ACCESS_KEY_ID!,
    secretAccessKey: env.STORAGE_S3_SECRET_ACCESS_KEY!,
    // Custom endpoints generally want bucket-in-path rather than a bucket
    // subdomain; AWS itself is fine either way.
    forcePathStyle: env.STORAGE_S3_FORCE_PATH_STYLE
      ? env.STORAGE_S3_FORCE_PATH_STYLE === "true"
      : Boolean(endpoint),
  };
}

/**
 * S3-compatible object storage: AWS S3, Cloudflare R2, Neon Object Storage,
 * MinIO — anything that speaks the S3 API. Set STORAGE_S3_ENDPOINT for a
 * non-AWS provider.
 *
 * Keys are the same application-generated keys the local driver uses, so a
 * bucket can be populated by copying the local storage directory into it and
 * switching the driver — no database rows change.
 */
class S3StorageAdapter implements StorageAdapter {
  readonly name = "s3";
  private readonly client: S3Client;
  private readonly bucket: string;

  constructor(config: S3Config) {
    this.bucket = config.bucket;
    this.client = new S3Client({
      region: config.region,
      endpoint: config.endpoint,
      forcePathStyle: config.forcePathStyle,
      credentials: {
        accessKeyId: config.accessKeyId,
        secretAccessKey: config.secretAccessKey,
      },
    });
  }

  async put(key: string, body: Buffer, contentType: string): Promise<StoredObject> {
    assertSafeKey(key);
    const safeKey = key;
    await this.client.send(
      new PutObjectCommand({
        Bucket: this.bucket,
        Key: safeKey,
        Body: body,
        ContentType: contentType,
        // Uploads are served through the app's own /media route, which applies
        // visibility rules; the object itself is never public.
        CacheControl: "private, max-age=0",
      }),
    );
    return { key: safeKey, size: body.byteLength };
  }

  async get(key: string): Promise<Buffer> {
    assertSafeKey(key);
    const response = await this.client.send(
      new GetObjectCommand({ Bucket: this.bucket, Key: key }),
    );
    if (!response.Body) throw new Error(`Empty object body for ${key}`);
    return Buffer.from(await response.Body.transformToByteArray());
  }

  async stream(key: string): Promise<Readable> {
    assertSafeKey(key);
    const response = await this.client.send(
      new GetObjectCommand({ Bucket: this.bucket, Key: key }),
    );
    if (!response.Body) throw new Error(`Empty object body for ${key}`);
    // In Node the SDK body is already a Readable; the cast documents that.
    return response.Body as Readable;
  }

  async delete(key: string): Promise<void> {
    assertSafeKey(key);
    await this.client.send(
      new DeleteObjectCommand({ Bucket: this.bucket, Key: key }),
    );
  }

  async exists(key: string): Promise<boolean> {
    assertSafeKey(key);
    try {
      await this.client.send(new HeadObjectCommand({ Bucket: this.bucket, Key: key }));
      return true;
    } catch (error) {
      if (isNotFound(error)) return false;
      throw error;
    }
  }

  async size(key: string): Promise<number> {
    assertSafeKey(key);
    const head = await this.client.send(
      new HeadObjectCommand({ Bucket: this.bucket, Key: key }),
    );
    return head.ContentLength ?? 0;
  }
}

function isNotFound(error: unknown): boolean {
  const name = (error as { name?: string; $metadata?: { httpStatusCode?: number } })?.name;
  const status = (error as { $metadata?: { httpStatusCode?: number } })?.$metadata?.httpStatusCode;
  return name === "NotFound" || name === "NoSuchKey" || status === 404;
}

function createStorageAdapter(): StorageAdapter {
  const driver = process.env.STORAGE_DRIVER ?? "local";

  switch (driver) {
    case "local":
      // A relative path is resolved against this project's root, never the
      // working directory. The website and the administration system must
      // read the same files, so on one machine both are given the same
      // absolute path (see .env.example).
      return new LocalStorageAdapter(
        fromProjectRoot(process.env.STORAGE_LOCAL_DIR ?? "storage"),
      );
    case "s3":
      return new S3StorageAdapter(readS3Config());
    default:
      throw new Error(
        `Unknown STORAGE_DRIVER "${driver}". Expected "local" or "s3".`,
      );
  }
}

const globalForStorage = globalThis as unknown as {
  storage?: StorageAdapter;
};

export const storage: StorageAdapter =
  globalForStorage.storage ?? createStorageAdapter();

if (process.env.NODE_ENV !== "production") {
  globalForStorage.storage = storage;
}

/**
 * Builds a collision-free object key. Nothing user-supplied reaches the path:
 * the folder is drawn from a fixed set by the caller and the basename is
 * random, so a hostile filename cannot influence where the file lands.
 */
export function buildStorageKey({
  folder,
  id,
  extension,
}: {
  folder: string;
  id: string;
  extension: string;
}): string {
  const now = new Date();
  const year = now.getUTCFullYear();
  const month = String(now.getUTCMonth() + 1).padStart(2, "0");
  const safeFolder = folder.replace(/[^a-z0-9-]/gi, "").toLowerCase() || "uploads";
  const safeExtension = extension.replace(/[^a-z0-9]/gi, "").toLowerCase() || "bin";

  return `${safeFolder}/${year}/${month}/${id}.${safeExtension}`;
}
