import "server-only";

import { fromRepoRoot } from "@bass/db/env";

import { createReadStream } from "node:fs";
import { mkdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { Readable } from "node:stream";

/**
 * Storage is abstracted so uploaded files can move from the local Docker
 * volume to S3-compatible object storage without touching call sites.
 *
 * Files are never written into `public/`: that directory is a build-time asset
 * folder, and anything placed there would be publicly readable regardless of
 * whether the record is marked private. Everything is served through a route
 * handler that applies authorisation.
 */

export type StoredObject = {
  key: string;
  size: number;
};

export interface StorageAdapter {
  readonly name: string;
  put(key: string, body: Buffer, contentType: string): Promise<StoredObject>;
  get(key: string): Promise<Buffer>;
  stream(key: string): Promise<Readable>;
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
  size(key: string): Promise<number>;
}

/**
 * Object keys are generated by the application, never taken from a filename.
 * This guards the boundary anyway, so a bug upstream cannot escape the root.
 */
export function assertSafeKey(key: string): void {
  if (!key || key.startsWith("/") || key.includes("\\")) {
    throw new Error(`Unsafe storage key: ${key}`);
  }
  const normalised = path.posix.normalize(key);
  if (
    normalised !== key ||
    normalised.split("/").some((segment) => segment === ".." || segment === "")
  ) {
    throw new Error(`Unsafe storage key: ${key}`);
  }
}

class LocalStorageAdapter implements StorageAdapter {
  readonly name = "local";
  private readonly root: string;

  constructor(root: string) {
    this.root = path.resolve(root);
  }

  private resolve(key: string): string {
    assertSafeKey(key);
    const full = path.resolve(this.root, key);
    // Defence in depth: the resolved path must stay inside the root.
    if (full !== this.root && !full.startsWith(this.root + path.sep)) {
      throw new Error(`Storage key escapes the storage root: ${key}`);
    }
    return full;
  }

  async put(key: string, body: Buffer): Promise<StoredObject> {
    const full = this.resolve(key);
    await mkdir(path.dirname(full), { recursive: true });
    await writeFile(full, body, { mode: 0o640 });
    return { key, size: body.byteLength };
  }

  async get(key: string): Promise<Buffer> {
    const { readFile } = await import("node:fs/promises");
    return readFile(this.resolve(key));
  }

  async stream(key: string): Promise<Readable> {
    const full = this.resolve(key);
    await stat(full); // surface a missing file before streaming starts
    return createReadStream(full);
  }

  async delete(key: string): Promise<void> {
    await rm(this.resolve(key), { force: true });
  }

  async exists(key: string): Promise<boolean> {
    try {
      await stat(this.resolve(key));
      return true;
    } catch {
      return false;
    }
  }

  async size(key: string): Promise<number> {
    const stats = await stat(this.resolve(key));
    return stats.size;
  }
}

/**
 * Placeholder for S3-compatible storage. It throws a clear, actionable error
 * rather than silently pretending to work — an unconfigured integration should
 * never look like a successful upload.
 */
class UnconfiguredS3Adapter implements StorageAdapter {
  readonly name = "s3";

  private fail(): never {
    throw new Error(
      "STORAGE_DRIVER is set to \"s3\", but the S3 adapter is not implemented yet. " +
        "Set STORAGE_DRIVER=local to use the mounted volume, or implement " +
        "src/lib/storage/index.ts::UnconfiguredS3Adapter.",
    );
  }

  put(): Promise<StoredObject> {
    this.fail();
  }
  get(): Promise<Buffer> {
    this.fail();
  }
  stream(): Promise<Readable> {
    this.fail();
  }
  delete(): Promise<void> {
    this.fail();
  }
  exists(): Promise<boolean> {
    this.fail();
  }
  size(): Promise<number> {
    this.fail();
  }
}

function createStorageAdapter(): StorageAdapter {
  const driver = process.env.STORAGE_DRIVER ?? "local";

  switch (driver) {
    case "local":
      // Resolved against the repository root, never the working directory:
      // the two apps and the CLI scripts all run from different places and
      // must share one storage directory.
      return new LocalStorageAdapter(
        fromRepoRoot(process.env.STORAGE_LOCAL_DIR ?? "storage"),
      );
    case "s3":
      return new UnconfiguredS3Adapter();
    default:
      throw new Error(
        `Unknown STORAGE_DRIVER "${driver}". Expected "local" or "s3".`,
      );
  }
}

const globalForStorage = globalThis as unknown as {
  storage?: StorageAdapter;
};

export const storage: StorageAdapter =
  globalForStorage.storage ?? createStorageAdapter();

if (process.env.NODE_ENV !== "production") {
  globalForStorage.storage = storage;
}

/**
 * Builds a collision-free object key. Nothing user-supplied reaches the path:
 * the folder is drawn from a fixed set by the caller and the basename is
 * random, so a hostile filename cannot influence where the file lands.
 */
export function buildStorageKey({
  folder,
  id,
  extension,
}: {
  folder: string;
  id: string;
  extension: string;
}): string {
  const now = new Date();
  const year = now.getUTCFullYear();
  const month = String(now.getUTCMonth() + 1).padStart(2, "0");
  const safeFolder = folder.replace(/[^a-z0-9-]/gi, "").toLowerCase() || "uploads";
  const safeExtension = extension.replace(/[^a-z0-9]/gi, "").toLowerCase() || "bin";

  return `${safeFolder}/${year}/${month}/${id}.${safeExtension}`;
}
