import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Creates the environment files each workspace needs from the single root
 * .env.
 *
 * Next.js only reads .env from its own application directory, so the two apps
 * each need their own copy. Rather than ask anyone to keep three files in step
 * by hand, the root .env stays the single source of truth and this copies it
 * outward. Existing files are never overwritten.
 */
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const source = path.join(root, ".env");

if (!existsSync(source)) {
  if (!existsSync(path.join(root, ".env.example"))) {
    console.error("No .env or .env.example found at the repository root.");
    process.exit(1);
  }
  copyFileSync(path.join(root, ".env.example"), source);
  console.log("Created .env from .env.example — fill in SESSION_SECRET.");
}

const contents = readFileSync(source, "utf8");
const banner =
  "# Generated by `npm run setup:env` from the repository root .env.\n" +
  "# Edit the root .env and re-run that command rather than editing this file.\n\n";

for (const app of ["apps/web", "apps/admin"]) {
  const target = path.join(root, app, ".env");
  if (existsSync(target)) {
    console.log(`${app}/.env already exists — left alone.`);
    continue;
  }
  writeFileSync(target, banner + contents);
  console.log(`Wrote ${app}/.env`);
}
