-- Full-text search support for site search.
-- Prisma has no native tsvector type, so the column is declared here and
-- mirrored in schema.prisma as Unsupported("tsvector").

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Weighted, always-current search vector. Generated by Postgres, never written
-- by the application, so it can never drift from the indexed columns.
ALTER TABLE "search_documents"
  ADD COLUMN "tsv" tsvector
  GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce("title", '')), 'A') ||
    setweight(to_tsvector('english', coalesce("keywords", '')), 'B') ||
    setweight(to_tsvector('english', coalesce("excerpt", '')), 'C')
  ) STORED;

CREATE INDEX "search_documents_tsv_idx" ON "search_documents" USING GIN ("tsv");

-- Trigram index for fuzzy applicant lookup in the admin applications table.
CREATE INDEX "applications_name_trgm_idx"
  ON "applications" USING GIN (
    (coalesce("firstName", '') || ' ' || coalesce("lastName", '')) gin_trgm_ops
  );
